// Auto-generated by setup wizard
// Edit this file to customize your brand

export const brand = {
  name: "IndieHire",
  tagline: "India's Freelancer Marketplace",
  description: "India's Freelancer Marketplace",

  product: {
    name: "IndieHire",
    version: "1.0.0",
    url: process.env.NEXT_PUBLIC_APP_URL || "https://yourapp.com",
  },

  company: {
    legalName: "IndieHire Private Limited",
    gstin: "YOUR_GSTIN_HERE",
    address: {
      line1: "123 Business Park",
      city: "Bangalore",
      state: "Karnataka",
      stateCode: "KA",
      pincode: "560001",
      country: "India",
    },
    pan: "YOUR_PAN_HERE",
  },

  contact: {
    email: "support@indiehire.com",
    phone: "+91-XXXXXXXXXX",
    supportUrl: "/support",
  },

  email: {
    fromSupport: "IndieHire Support <support@indiehire.com>",
    fromBilling: "IndieHire Billing <billing@example.com>",
    fromNoReply: "IndieHire <noreply@example.com>",
    replyTo: "support@indiehire.com",
  },

  pricing: {
    currency: "INR",
    currencySymbol: "₹",
    locale: "en-IN",
  },

  social: {
    twitter: "",
    github: "",
    discord: "",
  },

  inngest: {
    appId: process.env.INNGEST_APP_ID || "indiehire",
    appName: "IndieHire Background Jobs",
  },

  invoice: {
    sacCode: "998314", // SAC code for IT services
  },

  seo: {
    title: "IndieHire - India's Freelancer Marketplace",
    description: "India's Freelancer Marketplace",
    keywords: ["saas", "nextjs", "india", "boilerplate"],
    ogImage: "/og-image.png",
    twitterHandle: "",
  },
};

export function formatPrice(amountInPaise: number): string {
  const amountInRupees = amountInPaise / 100;
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: brand.pricing.currency,
    minimumFractionDigits: 0,
  }).format(amountInRupees);
}

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat(brand.pricing.locale, {
    style: "currency",
    currency: brand.pricing.currency,
    minimumFractionDigits: 0,
  }).format(amount);
}

export function generateInvoiceNumber(licenseId: string): string {
  const date = new Date();
  const year = date.getFullYear().toString().slice(-2);
  const month = (date.getMonth() + 1).toString().padStart(2, "0");
  const shortId = licenseId.slice(-8).toUpperCase();
  return `INV-${year}${month}-${shortId}`;
}
